Repository googleapis/python-iot, pull requests merged in 2021-04, with the labels that each got.

#86 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudiot, cla: yes, context: full

#88 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#91 feat: add blunderbuss config to cloud iot label
  .github/blunderbuss.yml
Labels: api: cloudiot, cla: yes

#94 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudiot, cla: yes

#90 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  samples/api-client/manager/noxfile.py
  synth.metadata
Labels: api: cloudiot, cla: yes, context: full, samples

#97 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudiot, cla: yes
