Repository googleapis/python-iot, pull requests merged in 2021-09, with the labels that each got.

#186 chore: revert owlbot main branch templates
  owlbot.py
Labels: api: cloudiot, cla: yes

#187 chore: reference main branch of google-cloud-python
  README.rst
Labels: api: cloudiot, cla: yes

#149 feat: Added python sample codes for cloud-iot-token-service generateAccessToken API
  samples/api-client/accesstoken_example/README.rst
  samples/api-client/accesstoken_example/README.rst.in
  samples/api-client/accesstoken_example/accesstoken.py
  samples/api-client/accesstoken_example/accesstoken_test.py
  samples/api-client/accesstoken_example/noxfile.py
  samples/api-client/accesstoken_example/requirements-test.txt
  samples/api-client/accesstoken_example/requirements.txt
  samples/api-client/accesstoken_example/resources/logo.png
  samples/api-client/accesstoken_example/resources/roots.pem
  samples/api-client/accesstoken_example/resources/rsa_cert.pem
  samples/api-client/accesstoken_example/resources/rsa_private.pem
Labels: api: cloudiot, cla: yes, samples

#193 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: api: cloudiot, cla: yes, automerge
