Repository googleapis/python-iot, pull requests merged in 2022-01, with the labels that each got.

#219 chore: update doc links from googleapis.dev to cloud.google.com
  .repo-metadata.json
  README.rst
Labels: api: cloudiot, cla: yes, automerge

#220 feat: add support for Python 3.9 / 3.10
  setup.py
Labels: api: cloudiot, cla: yes, automerge

#226 chore: add api_shortname to repo-metadata.json
  .repo-metadata.json
Labels: api: cloudiot, automerge

#243 chore: make samples 3.6 check optional
  .github/sync-repo-settings.yaml
Labels: api: cloudiot, samples

#245 docs(samples): modify accesstoken flow to use environment identity during setup
  samples/api-client/accesstoken_example/accesstoken.py
Labels: api: cloudiot
